data:
  image: gliderlabs/alpine
  command: echo Data Container

dbstate:
  extends:
    file: docker-compose.yml
    service: data
  volumes:
    - /data

db:
  image: postgres
  volumes_from:
    - dbstate
  environment:
    - PGDATA=/data
    - POSTGRES_PASSWORD=development

proxy:
  image: nginx:latest
  volumes:
    - ./proxy/app.conf:/etc/nginx/conf.d/app.conf
  ports:
    - "8080:8080"
  links:
    - coffee

coffee:
  build: ./coffee
  expose:
    - 3000
  links:
    - db:db
  environment:
    - COFFEEFINDER_DB_URI=postgresql://postgres:development@db:5432/postgres
    - COFFEEFINDER_CONFIG=development
    - SERVICE_NAME=coffee
